---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    run: flat
  name: flat-server-config
  namespace: mc-flat
data:
  ALLOW_NETHER: "false"
  COPY_CONFIG_DEST: /data #copy configfiles directly into /data, instead of /data/config
  DEBUG: "true"
  DEBUG_EXEC: "true"
  DIFFICULTY: peaceful
  ENABLE_AUTOPAUSE: "false"
  ENABLE_COMMAND_BLOCK: "false"
  ENABLE_ROLLING_LOGS: "true"
  EULA: "true"
  FORGEVERSION: RECOMMENDED
  GENERATE_STRUCTURES: "false"
  ICON: https://icons.iconarchive.com/icons/dakirby309/simply-styled/128/Minecraft-icon.png
  INITIAL_DELAY: 10m
  JVM_DD_OPTS: log4j2.formatMsgNoLookups=true
  MAX_PLAYERS: "6"
  MAX_TICK_TIME: "-1"
  MAX_WORLD_SIZE: "6000"
  MEMORY: 4G
  MODE: creative
  MOTD: flat
  ONLINE_MODE: "false"
  OPS: nerobrian
  OVERRIDE_SERVER_PROPERTIES: "true"
  PVP: "false"
  RCON_CMDS_STARTUP: |
    gamerule keepInventory true
    gamerule loadAdminCommands true
    gamerule doFireTick false
    gamerule doDaylightCycle false
    gamerule doInsomnia false
    gamerule doWeatherCycle false
  RCON_PASSWORD: minecraft
  RCON_PORT: "25575"
  SERVER_NAME: flat
  SPAWN_ANIMALS: "false"
  SPAWN_MONSTERS: "false"
  SPAWN_NPCS: "false"
  SPAWN_PROTECTION: "1"
  SRC_DIR: /data
  SYNC_SKIP_NEWER_IN_DESTINATION: "true"
  TUNE_VIRTUALIZED: "true"
  TYPE: PUFFERFISH #PAPER
  PUFFERFISH_BUILD: "46"
  USE_AIKAR_FLAGS: "true"
  VERSION: 1.20.4 #1.20.1
  VIEW_DISTANCE: "12"
  SIMULATION_DISTANCE: "5"
  LEVEL_TYPE: "minecraft:flat"
  FORCE_GAMEMODE: "true"
  BACKUP_NAME: "flat"
  NETWORK_COMPRESSION_THRESHOLD: "-1" #Disable Compression behind proxy
