---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: stop-flat
  namespace: mc-flat
spec:
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 30
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: stop
            image: harbor.lab.brianragazzi.com/cache/bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl exec -n mc-flat flat-0 -c server -- rcon-cli "stop"
          restartPolicy: Never #OnFailure
