apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    run: flat
  name: flat
  namespace: mc-flat
spec:
  routes:
  - conditions:
    - prefix: /flat
    pathRewritePolicy:
      replacePrefix:
      - prefix: /flat
        replacement: /
    services:
    - name: flat
      port: 8123
