---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-flat-data
  namespace: mc-flat
spec:
  storageClassName: tanzu
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
