---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: flat
  name: flat
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flat
  template:
    metadata:
      labels:
        run: flat
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: flat-server-config
          image: itzg/minecraft-server
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - mc-health
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 5
          name: server
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 8123
              protocol: TCP
            - containerPort: 25575
              protocol: TCP
          resources:
            requests:
              memory: "4Gi"
              cpu: "0.2"
            limits:
              memory: "6Gi"
              cpu: "2"
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /data
              name: server-data
        - envFrom:
            - configMapRef:
                name: backup-config-flat
          image: itzg/mc-backup
          imagePullPolicy: Always
          name: backup
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: server-data
              readOnly: true
            - mountPath: /backups
              name: mc-backups
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: server-data
          hostPath:
            path: /minecraft/flat-data
            type: ""
        - name: mc-backups
          nfs:
            server: 192.168.1.41
            path: /nfs/kubevol/mc-backups
        - name: configfiles
          configmap:
             name: flat-configfiles
        - name: plugins
          nfs:
            path: /nfs/kubevols/mc-plugins/flat
            server: 192.168.1.41
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
