---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bedrock-data
  namespace: bedrock
spec:
  storageClassName: tanzu
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
