---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bedrock.games.ragazzilab.com
  labels:
    run: bedrock
  name: bedrock-lb
  namespace: bedrock
spec:
  selector:
    run: bedrock
  ports:
    - port: 19132
      protocol: UDP
  ipFamilies:
    - IPv4
  # Use LoadBalancer if running on a provider that supports that
#  type: LoadBalancer
  # or use NodePort on a non-managed system;
  # however, you'll need to lookup port assigned to the service
  type: LoadBalancer
