---
apiVersion: v1
kind: Service
metadata:
  name: hugo-lablinks
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: lablinks.ragazzilab.com
  labels:
    app: hugo-lablinks
spec:
  type: ClusterIP
  ports:
  - port: 1313
    protocol: TCP
    targetPort: 1313
  selector:
    app: hugo-lablinks
