apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: mc-survive
    pod-security.kubernetes.io/enforce: privileged
  name: minecraft
spec:
  finalizers:
    - kubernetes
