---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mc-survive1
  name: jobrunner
rules:
- apiGroups: ["extensions", "apps", ""]
  resources:
  - deployments
  - statefulsets
  - pods
  - pods/exec
  - job
  verbs:
  - 'exec'
  - 'get'
  - 'list'
  - 'create'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobrunner
  namespace: mc-survive1
subjects:
- kind: ServiceAccount
  name: default
  namespace: mc-survive1
roleRef:
  kind: Role
  name: jobrunner
  apiGroup: rbac.authorization.k8s.io
