---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: survive1
  name: survive1
  namespace: mc-survive1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: survive1
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes-excludes: mc-backups,plugins
      labels:
        run: survive1
        type: minecraft
    spec:
      initContainers:
        - name: restore
          envFrom:
            - configMapRef:
                name: backup-config-survive1
          image: harbor.lab.brianragazzi.com/cache/itzg/mc-backup
          imagePullPolicy: IfNotPresent
          resources: {}
          command:
          - /bin/bash
          - -euc
          - |
            #!/bin/bash
            set -euo pipefail
            : "${SRC_DIR:=/data}"
            : "${DEST_DIR:=/backups}"
            : "${DEBUG:=false}"
            if [[ ${DEBUG,,} = true ]]; then
              set -x
            fi
            # shellcheck disable=SC2012
            if (( $(ls "$SRC_DIR/server.properties" | wc -l) == 0 )); then
              if (( $(ls "$DEST_DIR" | wc -l) > 0 )); then
                src=$(ls -t "$DEST_DIR" | head -1)
                echo "Restoring from $src"
                tar -x -m --no-overwrite-dir -f $src -C "$SRC_DIR"
              else
                echo "No backups available to restore"
              fi
            else
              echo "No restore needed.  server.properties exists"
            fi
          volumeMounts:
            - mountPath: /data
              name: server-data
            - mountPath: /backups
              name: mc-backups
              readOnly: true
      containers:
        - name: server
          envFrom:
            - configMapRef:
                name: survive1-server-config
          image: harbor.lab.brianragazzi.com/cache/itzg/minecraft-server:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - mc-health
            failureThreshold: 5
            initialDelaySeconds: 90
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 8123
              protocol: TCP
            - containerPort: 25575
              protocol: TCP
            - containerPort: 8100
              protocol: TCP
          resources:
            requests:
              memory: "11Gi"
              cpu: "500m"
            limits:
              memory: "11Gi"
              cpu: "3"
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - name: server-data
              mountPath: /data
            - name: plugins
              mountPath: /plugins
              subPath: survive1/
              readOnly: true
            - name: configfiles
              mountPath: /config
        - name: backup
          envFrom:
            - configMapRef:
                name: backup-config-survive1
          image: harbor.lab.brianragazzi.com/cache/itzg/mc-backup
          imagePullPolicy: IfNotPresent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: server-data
              readOnly: true
            - mountPath: /backups
              name: mc-backups
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 501
        runAsGroup: 501
        runAsUser: 501
      terminationGracePeriodSeconds: 30
      volumes:
        - name: server-data
          persistentVolumeClaim:
            claimName: pvc-survive1-data
        - name: mc-backups
          nfs:
            server: 192.168.1.41
            path: /nfs/kubevol/mc-backups/survive1 # this is set to the folder containing this server's backups
            readOnly: false
        - name: configfiles
          configMap:
             name: survive1-configfiles
        - name: plugins
          nfs:
            path: /nfs/kubevol/mc-plugins
            server: 192.168.1.41
            readOnly: true
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
