apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-xmage-pipeline
  namespace: pipelines
spec:
  workspaces:
    - name: shared-data
    - name: docker-credentials
      description: docker config
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: main
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: $(tasks.getversion.results.xmage_version)
    - name: kanikoExtraArgs
      type: array
  tasks:
    - name: getversion
      taskRef:
        name: task-xmageversion
    - name: fetch-repo
      taskRef:
        name: git-clone
      runAfter:
        - getversion
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: deleteExisting
          value: "true"
    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(tasks.getversion.results.xmage_version)
        - name: EXTRA_ARGS
          value:
           - $(params.kanikoExtraArgs[*])
