apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  #generateName: hugo-build-
  generateName: lablinks-build
  namespace: pipelines
spec:
  pipelineRef:
    name: image-build-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: gitUrl
      value: https://github.com/BrianRagazzi/homelab
    - name: gitRevision
      value: master
    - name: pathToContext
      value: images/newhugo
    - name: imageUrl
      value: harbor.lab.brianragazzi.com/library/lablinks #ragazzilab/docker-xmagebeta-alpine
    - name: imageTag
      value: "latest"
    - name: kanikoExtraArgs
      value:
        - "--verbosity=debug"
  serviceAccountName: pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: harbor
