---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: survive2
  name: survive2
  namespace: minecraft
spec:
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: prometheus
      port: 9940
      protocol: TCP
      targetPort: 9940
    - name: dynmap
      port: 80
      protocol: TCP
      targetPort: 8123
  selector:
    run: survive2
  type: ClusterIP
