apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: xmage.games.ragazzilab.com
  labels:
    run: xmage
  name: xmage-lb
  namespace: xmage
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: primary
      port: 17171
      protocol: TCP
      targetPort: 17171
    - name: secondary
      port: 17179
      protocol: TCP
      targetPort: 17179
  selector:
    run: xmage
  sessionAffinity: None
  type: LoadBalancer
