apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: xmage
  name: xmage
  namespace: xmage
spec:
  replicas: 1
  selector:
    matchLabels:
      run: xmage
  template:
    metadata:
      labels:
        run: xmage
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: xmage-env
          image: ragazzilab/xmagetoday:latest
          imagePullPolicy: Always
          name: xmage
          ports:
            - containerPort: 17171
              name: primary
              protocol: TCP
            - containerPort: 17179
              name: secondary
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512M
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
