apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: waterfall
    pod-security.kubernetes.io/enforce: privileged
    app.kubernetes.io/name: waterfall
  name: waterfall
spec:
  finalizers:
    - kubernetes
