---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: waterfall.games.ragazzilab.com
  labels:
    run: waterfall
  name: waterfall-lb
  namespace: waterfall
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
    name: minecraft
  - port: 9985
    protocol: TCP
    targetPort: 9985
    name: prometheus
  selector:
    run: waterfall
