---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgCBvOKdgDXwRQH/P1TEop2+PIQ8ofIY5zVoXQuygxJadzles/lhn9WsMm/wOf6I8javJyWiu7x1/nKSEHXwVerySwCiml1hT8JlhyEn6KffnD/hUrKh/Uu5d6bjRKKaLY3+eP3SIgziOahs7GaYvTTMEAJlXLtuiuUqHJtBkxTn2pETX4baq+nnEHfHYXdUf6C9Ow/5p3ypcRHk14fM3WHtd8BtXmMkJ9ezszaJiBTzUC0f4HyJHYdn+n5EYJaN0UVUW2oIhWbeINxRB3hVfO7nKg/0ZBs7ATGVUC/KlB7twxr660NXLUi/myGCBwfPIaZUX9Q+VbIIiahbpDZRIiXIRhsC89dMjA0eyb+jtlF+f22xnUGFz8Cc6xKqaE0RxRTOAd1ZSY4LsVWdklrdagym6gr/BYfzz5TJaeXYvOU/WO7MRWJ5vfVEMJbPQ4UvsEtwplkZJ7n9ntA0evqDBLaykLQRwf3ajkUd+vgD7l5eIXOM046CqHQVje47aRtoKRa5rB0ep23iPCgK0lo2khFoWomPjTM1bWYhiD7HlIvEhv6zcJ+6spZFrh1R079ttZjx8H9JeT8RKUaBph4g0u5nSfe0XiNpP+Mcu3AECR9+mOp/H4a+ErkGw3302BQggw/9FWg+OYUoLxBG4u91ViiIh6anqgERBl7fF8Wsp7+fUOPojpEMB9uDqIG/AVP2I4FUlKzA5THtrjI=
    user: AgAjqcgkZCD8htsXwuFeNgXZR87Ij6BGrExKj7xo3/qeRMfX1TYiUlofuboubCFpS4pmnz5CaYjDnZD1xxbX1IQub6OF7U3xZRBq7Kn8CMYnMzlUKRUPu+AMRPisOZJWY9Z1JHXSysWhYv+zpKwuoYZseNiBGuEEm9DBNg7EGi+l96La9Bq1FtGIscK3RpUwEM+yv+8Mg6jQ1CK7KPKxsQ6Iko/M47V/Z6cx0RhtJcaeFnE8rVTdeWzkL2kp/scxFJ6Z0LEVNfd2+oAOI6gNfjdN8cPibhOCjoZ9lvC+9fGdGvi9u4L3O/vIlJ8BrePd0rgIJaY+0pUnuI/FEW/rESHbg3BCJ2w9z/K5LzKQDYRpcBCIMk/hBqP36TJv8rjK+Ro2L/Eze5RntamBiRqza/c2wy/x5LG76XAMN8EJnesyHlEe+EWyw57QC2QQKaiQUrBlZCyEXBYQDqvtxii2FHsxo7m9oHeZ2kTG2wm65u4ltuFpbkgz5wgQc0vj5o1BKW2qMVW33U4qLFaX8nq5TVQ0yYZbwUZFf1+rEeDtkMWPHcCSVGX0RzhBpjgDq0crAL9qMk2NLopnYO00VA3paJrbF7lghnKU8mRZhUsY4NtjKgeQunbqotXkHzFwkZtq4aO0qjBF1zeCimu2O47HSXb1JnItLG1VjHKzzzqD/nrh6iCtFdwZYJOPsFVCkcz7tKadwJbHVg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default
