apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  labels:
    tmc.cloud.vmware.com/managed-helm-release-name: sealed-secrets
  name: sealed-secrets
  namespace: tanzu-helm-resources
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 1.12.1
  install:
    createNamespace: true
  interval: 10m0s
  serviceAccountName: sealed-secrets-c7d78ab
  targetNamespace: flux-helm
  valuesFrom:
    - kind: Secret
      name: sealed-secrets-c7d78ab
      valuesKey: inline-configurations
